//player choose "rock", "paper", or "scissors".
//computer generates randomly one of the three options.
//compare player choice with computer and define winner. Show also what was generated by computer.
//store points for player and computer.
//repeat utill player or computer gets 5 points.
//announce the winner.

//Get player choice:

let getPlayerChoice = prompt('What is your choice?');

    //console.log(getPlayerChoice);



//Function to generate computer choice:

function getComputerChoice() {
    let choices = ['Rock', 'Paper', 'Scissors'];
    let computerNumber = Math.floor(Math.random() * choices.length);

    let computerChoice = choices[computerNumber];

    return computerChoice;
}

    //console.log(getComputerChoice());